version: '3.8'  # Adjust the version as needed

services:
  my_python_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "8501:8501"
    command: streamlit run demo.py

